# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

schedules:
  - cron: "0 4 * * 1-5"
    displayName: "Daily Automatic Pipeline Run"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: ubuntu-latest

parameters:
  - name: SECRET_KEY2
    displayName: 'Select Script Key'
    type: string
    default: 'ui_api_chrome'
    values:
      - ui_api_chrome
      - ui_qa_chrome_headed
      - ui_api_chrome_headed
      - ui_api_chrome_firefox



steps:
- task: UseNode@1
  inputs:
    versionSource: 'spec'
    version: '22.x'

- script: npm ci
  displayName: 'Install Playwright Dependencies'

- script: npx playwright install --with-deps
  displayName: 'Install Playwright Browsers'

#- script: SECRET_KEY=$(SECRET_KEY) npm run $(SCRIPT_KEY)
- script: SECRET_KEY=$(SECRET_KEY) npm run ${{parameters.SECRET_KEY2}}
  displayName: 'Run Tests'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'playwright-report'
    artifact: 'playwright-report'
    publishLocation: 'pipeline'
  condition: always()

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**test-results/junit-report.xml'
    testRunTitle: 'Playwright Junit report'
  condition: always()